password:
    yaoshiu@NixOS: ENC[AES256_GCM,data:TqjaiDkGqnFvimauAxXmfS3AKIGCXAsmi4Maj6nQ4ybmxuiRNVZ82U62N7MKNiFSNvC9SvxqO8g78DvnkcKRV/5i6rEx3NwD6Q==,iv:hauCfLKGP0oJjCDQHUIHD4x/slqamQZT7saAbHpxCYs=,tag:hL/yr6Q/CG69PbRdwUiOVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qsg6p8wh2ggjqxxnfv93y6rxmzc5mcdwknmjudzqxpwe6wefepwqxcaee4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MmdoZU1sTHZkK3o4Tml2
            UXpxc3cybWVRVlkrcWM4ODhQL2g2WG9oOWhzCkFFTENueWg4S3JEazRvbnJ6R2lB
            Z0kzTjNzUllnNWloK3BreWRweWFRTUEKLS0tIHIrRmYxeTJ4YjdZWW95bGMxU1A3
            RUxrSlE0K2JVdy9CbE92b3dQNitCZWcKIygUBfkv7XICAMIdIPLha27fE/GAntCF
            5pUtDsvZRP/ERPSrCTWvKTbXnuuVPhZmkUBNmmN9rD7YwscUoTTJMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qdj9y86tpps96uzxkyq6wynnwdkr0jlt28pqdey23uj30axs8arqpzsfu9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb0EzNVRJU0dzbVdLdzJq
            NEo0M283N1RCdS9GbisxK09jRFVPangrV0c4CnlhVm9TSjlyYktZMUk4TEVTWDFo
            VmttN09MSUdoOWpudnVRWlRxM0VEN00KLS0tIFZSOE5PMEZocXZ4Z2NZc2lkNHR6
            R0l0NDFNeUVoUmNMMEhDOGNTZlB4RGcK2c5RRvyKc2ASwaekEyogB5FbjvvoN2SX
            JfrZYg8u+OHneFF/Er8B2+qmn0KBTNFzC/dZPMSdiKQK0XZvJjK+VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T09:12:26Z"
    mac: ENC[AES256_GCM,data:Ry46yPm5N72c31cwYpo6sj6fOic67FJ0lGodiy94o7tJkE+xlZrWipY4Ot8K35+QYAjgzOIJizDMNDkRWlou6+2XlC62Ce6D46r2e8GN6ctn8zA2zlUJUqO+MCyOTBZ0CUOQG7CG5Rvfp4wvMIN3ojLs9Pcs9Vm6UzcAH539328=,iv:SVEX/Ot+p2Vre8EzJYSiw9yvBbxkkYW2C0a0HPkz7GA=,tag:VAZk3Dj/kabFFY/F8KNkrw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
