{
  config,
  lib,
  ...
}: let
  cfg = config.programs.wezterm;
in {
  config = lib.mkIf cfg.enable {
    xdg.configFile."wezterm/wezterm.lua".text = lib.mkForce ''
      -- Generated by Home Manager.
      -- See https://wezfurlong.org/wezterm/
      local wezterm = require 'wezterm';
      local config = wezterm.config_builder()

      ${cfg.extraConfig}

      return config
    '';
  };
}
